### ISSUE TITLE
プレイヤーの修正について

### ISSUE THREAD

**Issue by waflan** [SystemEngineeringTeam/creative-project2022-teamA#20]
プレイヤーの大きさは縦２ブロック未満、横１ブロック未満に変更
プレイヤーのゲームオブジェクトにタグ"Player"をつけておく
カプセルコライダからボックスコライダに変えてほしい(地形の角で滑り落ちるから)
地面判定のトリガーの横幅がコライダより大きくて崖に引っかかる
壁ジャンプが反転せず無限にジャンプできるバグを直して欲しい
背面での壁くっつきを修正して欲しい

**Comment by wdtkr** [comment]
プレイヤーの大きさは縦２ブロック未満、横１ブロック未満に変更
☑プレイヤーのゲームオブジェクトにタグ"Player"をつけておく
☑カプセルコライダからボックスコライダに変えてほしい(地形の角で滑り落ちるから)
☑地面判定のトリガーの横幅がコライダより大きくて崖に引っかかる
☑壁ジャンプが反転せず無限にジャンプできるバグを直して欲しい
☑背面での壁くっつきを修正して欲しい
